services:
  - type: web
    name: video-app-learning
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MEDIASOUP_LISTEN_IP
        value: 0.0.0.0
      - key: PORT
        value: 3000
      - key: METERED_API_KEY
        value: 35bc0752073676aafcc58f20471787c3a1ab