services:
  - type: web
    name: video-app-learning
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MEDIASOUP_LISTEN_IP
        value: 0.0.0.0
      - key: PORT
        value: 3000